.PHONY: clean All

All:
	@echo "----------Building project:[ styrcheck - Debug ]----------"
	@"$(MAKE)" -f  "styrcheck.mk"
clean:
	@echo "----------Cleaning project:[ styrcheck - Debug ]----------"
	@"$(MAKE)" -f  "styrcheck.mk" clean
