.PHONY: clean All

All:
	@echo "----------Building project:[ process - Debug ]----------"
	@"$(MAKE)" -f  "process.mk"
clean:
	@echo "----------Cleaning project:[ process - Debug ]----------"
	@"$(MAKE)" -f  "process.mk" clean
