.PHONY: clean All

All:
	@echo "----------Building project:[ convert - Debug ]----------"
	@"$(MAKE)" -f  "convert.mk"
clean:
	@echo "----------Cleaning project:[ convert - Debug ]----------"
	@"$(MAKE)" -f  "convert.mk" clean
